services:
  app:
    container_name: app
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  celery_worker_1:
    container_name: celery_worker_1
    build: .
    command: celery -A tasks worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  celery_worker_2:
    container_name: celery_worker_2
    build: .
    command: celery -A tasks worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  celery_worker_3:
    container_name: celery_worker_3
    build: .
    command: celery -A tasks worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  flower:
    container_name: flower
    build: .
    command: celery -A tasks flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery_worker_1
      - celery_worker_2
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
